wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702640298.625428
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 4
      - 23
      - 42
      4: 3.9.16
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
dataset:
  desc: null
  value: square_jamendo_data
epochs:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 5
lr:
  desc: null
  value: 1.0e-05
num_layers:
  desc: null
  value: 10
dim_feedforward:
  desc: null
  value: 128
architecture:
  desc: null
  value: transformer
