wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702440313.56379
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 4
      - 5
      13: darwin-arm64
dataset:
  desc: null
  value: square_jamendo_data
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.001
num_layers:
  desc: null
  value: 10
architecture:
  desc: null
  value: transformer
